import json, io, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = "F:/做一个官网网页/"
data = {
  "en": {
    "第十届中国国际工业展览会Wire Show 2017": "The 10th China International Wire & Cable Industry Fair (Wire Show 2017)",
    "2018年德国杜塞尔多夫国际管材、线缆展 Tube &amp; Wire 2018": "Tube &amp; Wire 2018, Düsseldorf, Germany",
    "东莞市庆丰电工机械有限公司“2019年企业标准”声明公示": "Dongguan Qingfeng Electrical Machinery '2019 Enterprise Standard' Public Declaration",
    "塑料挤出机的基本原理": "Basic Principles of Plastic Extruders",
    "新能源汽车推动线缆市场发展，行业未来发展潜力巨大": "New Energy Vehicles Drive Cable Market Growth with Huge Potential",
    "电线电缆基础性能": "Basic Performance of Wire and Cable",
    "新能源汽车线束": "New Energy Vehicle Wiring Harness",
    "如何能设计出符合摇摆及弯曲试验性能的线材": "How to Design Wire That Meets Flexing and Bending Test Requirements",
    "线缆行业未来的发展趋势": "Future Development Trends of the Cable Industry",
    "绕包机厂家讲述电动汽车充电桩电缆": "Taping Machine Manufacturer Explains EV Charging Pile Cables",
    "高频线如何衰减": "How High-Frequency Cables Attenuate",
    "押出机生产设备操作工工作须知的内容": "Work Instructions for Extruder Machine Operators",
    "有关绞线机的运行原理的介绍": "Introduction to the Operating Principle of Stranding Machines",
    "笼绞机和框绞机究竟有什么不同": "What Is the Difference Between a Cage Strander and a Rigid Frame Strander",
    "绕包机组合安装在无轴升降放线机你知道吗？": "Do You Know About Installing a Taping Machine on a Shaftless Lifting Payoff?",
    "电缆挤出机的操作、维护与保养": "Operation, Maintenance and Care of Cable Extruders",
    "绞线机厂家介绍全自动高速绞线机主轴的调整方式": "Stranding Machine Manufacturer Explains How to Adjust the Spindle of an Automatic High-Speed Stranding Machine",
    "押出机生产过程常见的问题和怎样去处理？": "Common Problems in Extruder Production and How to Handle Them",
    "绞线机工艺流程及常见故障排除方法": "Stranding Machine Process Flow and Common Troubleshooting Methods",
    "笼绞机的常见问题及生产流程": "Common Problems and Production Process of Cage Stranders",
    "押出机要定期巡视检修": "Regular Inspection and Maintenance of Extruders",
    "电缆绞线机安全操作规程及会出现的故障有哪些？": "Safety Operating Procedures for Cable Stranding Machines and Common Faults",
    "笼绞机维护和保养": "Maintenance and Care of Cage Stranders",
    "关于绕包机云母带的绕层数和搭压率": "Number of Mica Tape Layers and Overlap Rate for Taping Machines",
    "精密绞线机常规问题处理": "Handling Common Problems of Precision Stranding Machines",
    "笼绞机的优点及适用范围": "Advantages and Applications of Cage Stranders",
    "绕包机厂家讲解绕包机成圈包装工艺操作规程": "Taping Machine Manufacturer Explains the Coiling &amp; Packaging Process Procedure",
    "庆丰将参加第七届中国国际线缆及线材展览会": "Qingfeng to Exhibit at the 7th China International Wire &amp; Cable Exhibition",
    "绕包机厂家来说说超五类双绞线与六类双绞线的区别比较": "Taping Machine Manufacturer Compares Cat5e and Cat6 Twisted Pair Cables",
    "绞线机绞线原理及绞距定义": "Stranding Principle and Lay Length Definition",
    "押出机设备生产作业员安全注意须知": "Safety Guidelines for Extruder Machine Operators",
    "庆丰将参加第六届印度国际线缆及线材展览会": "Qingfeng to Exhibit at the 6th India International Wire &amp; Cable Exhibition",
    "庆丰参加华南第一届新能源电动汽车充电线缆连接技术研讨会": "Qingfeng Attends the 1st South China New Energy EV Charging Cable Connection Technology Seminar",
    "我国光电线缆产业“十三五”期间仍将保持两成快速增长": "China's Optical &amp; Electrical Cable Industry to Keep ~20% Growth During the 13th Five-Year Plan",
    "2017第3届（东莞）国际电线电缆展览会": "2017 3rd (Dongguan) International Wire &amp; Cable Exhibition",
    "公司简介": "Company Profile",
    "董事长致辞": "Chairman's Message",
    "企业文化": "Corporate Culture",
    "资质荣誉": "Qualifications &amp; Honors",
    "证书展示": "Certificates",
    "厂区展示": "Factory Tour",
    "关于我们": "About Us",
    "新闻动态": "News",
    "联系我们": "Contact Us",
    "视频中心": "Video Center",
    "下载中心": "Downloads",
    "招聘人才": "Careers",
    "在线留言": "Leave a Message",
    "首页": "Home",
    "成功案例": "Case Studies"
  },
  "ja": {
    "第十届中国国际工业展览会Wire Show 2017": "第10回 中国国際ワイヤー・ケーブル産業展（Wire Show 2017）",
    "2018年德国杜塞尔多夫国际管材、线缆展 Tube &amp; Wire 2018": "チューブ＆ワイヤー 2018（ドイツ・デュッセルドルフ）",
    "东莞市庆丰电工机械有限公司“2019年企业标准”声明公示": "東莞市慶豊電工機械有限公司「2019年企業標準」公示",
    "塑料挤出机的基本原理": "プラスチック押出機の基本原理",
    "新能源汽车推动线缆市场发展，行业未来发展潜力巨大": "新エネ車がケーブル市場を牽引、今後の成長ポテンシャルは巨大",
    "电线电缆基础性能": "電線・ケーブルの基本性能",
    "新能源汽车线束": "新エネ車用ワイヤーハーネス",
    "如何能设计出符合摇摆及弯曲试验性能的线材": "揺動・屈曲試験性能を満たす電線の設計方法",
    "线缆行业未来的发展趋势": "ケーブル業界の今後の発展動向",
    "绕包机厂家讲述电动汽车充电桩电缆": "テープ巻機メーカーが語るEV充電スタンド用ケーブル",
    "高频线如何衰减": "高周波ケーブルの減衰とは",
    "押出机生产设备操作工工作须知的内容": "押出機オペレーターの作業心得",
    "有关绞线机的运行原理的介绍": "撚線機の動作原理のご紹介",
    "笼绞机和框绞机究竟有什么不同": "ケージ撚線機とリジッドフレーム撚線機の違いとは",
    "绕包机组合安装在无轴升降放线机你知道吗？": "無軸昇降ペイオフへのテープ巻機の組み合わせ設置をご存知ですか？",
    "电缆挤出机的操作、维护与保养": "ケーブル押出機の操作・保守・メンテナンス",
    "绞线机厂家介绍全自动高速绞线机主轴的调整方式": "撚線機メーカーが解説する全自動高速撚線機スピンドルの調整方法",
    "押出机生产过程常见的问题和怎样去处理？": "押出機生産工程でよくある問題と対処方法",
    "绞线机工艺流程及常见故障排除方法": "撚線機の工程フローとよくある故障の排除方法",
    "笼绞机的常见问题及生产流程": "ケージ撚線機のよくある問題と生産フロー",
    "押出机要定期巡视检修": "押出機の定期的な点検・整備",
    "电缆绞线机安全操作规程及会出现的故障有哪些？": "ケーブル撚線機の安全作業手順と発生しうる故障",
    "笼绞机维护和保养": "ケージ撚線機の保守とメンテナンス",
    "关于绕包机云母带的绕层数和搭压率": "テープ巻機におけるマイカテープの巻層数と重なり率",
    "精密绞线机常规问题处理": "精密撚線機の日常的な問題処理",
    "笼绞机的优点及适用范围": "ケージ撚線機の特長と適用範囲",
    "绕包机厂家讲解绕包机成圈包装工艺操作规程": "テープ巻機メーカーが解説する成巻・梱包工程の作業手順",
    "庆丰将参加第七届中国国际线缆及线材展览会": "慶豊、第7回中国国際ワイヤー・ケーブル展に出展",
    "绕包机厂家来说说超五类双绞线与六类双绞线的区别比较": "テープ巻機メーカーが語るCat5eとCat6ツイストペアの違い",
    "绞线机绞线原理及绞距定义": "撚線原理と撚りピッチの定義",
    "押出机设备生产作业员安全注意须知": "押出機オペレーターの安全注意事項",
    "庆丰将参加第六届印度国际线缆及线材展览会": "慶豊、第6回インド国際ワイヤー・ケーブル展に出展",
    "庆丰参加华南第一届新能源电动汽车充电线缆连接技术研讨会": "慶豊、第1回華南新エネEV充電ケーブル接続技術セミナーに参加",
    "我国光电线缆产业“十三五”期间仍将保持两成快速增长": "中国の光・電気ケーブル産業は第13次五カ年計画期間も約20%成長を維持",
    "2017第3届（东莞）国际电线电缆展览会": "2017 第3回（東莞）国際電線ケーブル展",
    "公司简介": "会社概要",
    "董事长致辞": "会長ご挨拶",
    "企业文化": "企業文化",
    "资质荣誉": "資格・栄誉",
    "证书展示": "証明書",
    "厂区展示": "工場紹介",
    "关于我们": "会社概要",
    "新闻动态": "ニュース",
    "联系我们": "お問い合わせ",
    "视频中心": "ビデオセンター",
    "下载中心": "ダウンロード",
    "招聘人才": "採用情報",
    "在线留言": "メッセージを送る",
    "首页": "ホーム",
    "成功案例": "導入事例"
  }
}
io.open(ROOT + "_i18n_titles.json", "w", encoding="utf-8").write(json.dumps(data, ensure_ascii=False, indent=1))
print("wrote titles:", {k: len(v) for k, v in data.items()})