import json, io, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = "F:/做一个官网网页/"
D = json.load(io.open(ROOT + "_i18n_body_en.json", encoding="utf-8"))

index_pairs = [
    # hero
    ("自 2000 年起 · 高频高速线缆装备制造商", "Since 2000 · High-Frequency & High-Speed Cable Machinery Manufacturer"),
    ("<span>高频高速</span>", "<span>High-Frequency &amp; High-Speed</span>"),          # h1 line
    ("<span>电线电缆设备</span>", "<span>Wire &amp; Cable Machinery</span>"),
    ("面向全球工厂客户，提供挤出、绞线、屏蔽、光缆等全系列线缆成套装备及定制化解决方案。",
     "A global supplier of complete extrusion, stranding, shielding and fiber-optic cable machinery lines plus custom-engineered solutions for factories worldwide."),
    ("浏览产品中心", "Browse Products"),
    ("了解更多", "Learn More"),                  # hero + about both use; replace both
    ("年制造经验", "Years of Experience"),
    ("出口国家", "Export Countries"),
    ("专业员工", "Skilled Employees"),
    ("自有厂房", "Own Factory Space"),
    # about
    ("关于我们", "About Us"),
    ("专注线缆装备<br>二十余年", "Focused on Cable Machinery<br>for Over 20 Years"),
    ("东莞市庆丰电工机械有限公司成立于 2000 年，是一家集电线、电缆、光缆设备技术研发、制造、服务为一体的高科技企业。",
     "Founded in 2000, Dongguan Qingfeng Electrical Machinery Co., Ltd. is a high-tech enterprise integrating R&amp;D, manufacturing and service of wire, cable and optical-fiber equipment."),
    ("拥有国内及国际两个销售团队，产品远销全球 30 多个国家和地区，致力于为客户提供售前、售中、售后的全系列服务。",
     "With both domestic and international sales teams, our products are exported to 30+ countries and regions, delivering full-service support from pre-sale through after-sale."),
    # products showcase
    ("产品展示", "Product Showcase"),
    ("高频高速", "High-Frequency &amp; High-Speed"),
    ("线缆装备系列", "Cable Machinery Series"),
    ("覆盖挤出、绞线、屏蔽、光缆等全系列电线电缆制造装备",
     "Complete wire &amp; cable manufacturing machinery across extrusion, stranding, shielding and fiber optics"),
    ("立式笼绞机", "Vertical Cage Strander"),
    ("适用于多种线缆结构的成缆绞合，结构稳定、绞合均匀。",
     "For cabling and stranding of various cable constructions. Stable structure, uniform stranding."),
    ("充电桩线缆绞线设备", "EV Charging Cable Stranding Machine"),
    ("专为新能源充电桩线缆生产设计，高效稳定。",
     "Specifically designed for new-energy charging pile cable production. Efficient and stable."),
    ("USB3.1 Type-C 挤出生产线", "USB3.1 Type-C Extrusion Line"),
    ("适用于高频数据线、同轴线等薄皮绝缘多层押出。",
     "For multi-layer thin-wall insulation extrusion of high-frequency data cables, coaxial cables, etc."),
    ("查看全部产品 →", "View All Products"),
    # product series
    ("产品系列", "Product Series"),
    ("八大系列 · 完整解决方案", "Eight Series · Complete Solutions"),
    ("挤出机系列", "Extruder Series"),
    ("绝缘芯线、护套线、铁氟龙、化学/物理发泡等押出生产线。",
     "Extrusion lines for core insulation, jacketing, PTFE and chemical/physical foam insulation."),
    ("绞线及成缆系列", "Stranding &amp; Cabling Series"),
    ("高速绞线机、旋臂单绞机、笼绞机、框绞机等。",
     "High-speed stranding machines, arm-type single twisters, cage stranders, rigid frame stranders, etc."),
    ("屏蔽系列", "Shielding Series"),
    ("立式/卧式包带机、高频线缆包带机及屏蔽设备。",
     "Vertical/horizontal taping machines, high-frequency cable taping machines and shielding equipment."),
    ("辐照交联设备", "Irradiation Cross-linking Equipment"),
    ("辐照交联生产的束下成套装备。",
     "Complete under-beam equipment for irradiation cross-linking production."),
    ("光缆设备系列", "Fiber-Optic Cable Series"),
    ("皮线光缆、紧包光纤、光缆护套等押出生产线。",
     "Extrusion lines for FTTH drop cable, tight-buffered fiber and optical cable sheathing."),
    ("成套设备系列", "Complete Line Series"),
    ("面向特定线缆产品的成套生产线整体方案。",
     "Turnkey production lines tailored to specific cable products."),
    ("辅助设备系列", "Auxiliary Equipment Series"),
    ("摇盘机、甩桶放线架、卷取机等配套装备。",
     "Coil winders, barrel payoffs, take-up machines and other supporting equipment."),
    ("新品推荐", "New Products"),
    ("新能源充电桩电缆设备、USB3.1 Type-C 设备等新品。",
     "New equipment for EV charging cables, USB3.1 Type-C and more."),
    # advantages
    ("我们的优势", "Our Advantages"),
    ("为什么选择", "Why Choose"),
    ("庆丰电工机械", "Qingfeng Electrical Machinery"),
    ("从方案设计到售后服务，为您提供全生命周期的价值保障",
     "Full-lifecycle value assurance, from design to after-sales service"),
    ("高新技术企业", "High-Tech Enterprise"),
    ("国家专利与省市科技进步奖数十项，产品被中国电器工业协会推介。",
     "Dozens of national patents and provincial/city science &amp; technology awards; products recommended by the China Electrical Equipment Industry Association."),
    ("按需定制方案", "Customized Solutions"),
    ("依据线缆结构与实际工艺要求，提供专业技术解决方案。",
     "Professional technical solutions based on your cable structure and process requirements."),
    ("国内国际双团队", "Domestic &amp; International Teams"),
    ("产品销往全球 30 多个国家和地区，服务响应快。",
     "Products exported to 30+ countries &amp; regions with fast service response."),
    ("全生命周期服务", "Full-Lifecycle Service"),
    ("从售前咨询、售中调试到售后维保，全程独立部门保障。",
     "Dedicated departments covering pre-sale consultation, commissioning and after-sales maintenance."),
    # cases
    ("成功案例", "Success Cases"),
    ("全球客户的信赖之选", "Trusted by Customers Worldwide"),
    ("EV 充电桩线缆笼绞设备在深圳某知名企业现场", "EV Charging Cable Cage Strander at a Leading Shenzhen Factory"),
    ("为深圳知名线缆企业提供新能源充电桩线缆专用笼绞设备。",
     "Custom cage stranding equipment for EV charging cables, delivered to a leading Shenzhen cable maker."),
    ("出口美国 300 笼绞机一次试机成功", "300 Cage Strander for the USA Passed Trial on First Run"),
    ("出口美国的 300 笼绞机一次试机成功，获客户高度认可。",
     "Our 300 cage strander exported to the USA passed trial operation on first run, highly recognized by the customer."),
    ("查看全部案例", "View All Cases"),
    # news
    ("新闻动态", "News &amp; Updates"),
    ("行业技术与企业动态", "Industry Technology &amp; Company News"),
    ("行业技术", "Technology"),
    ("企业新闻", "Company"),
    ("绞线机厂家介绍全自动高速绞线机主轴的调整方式",
     "How to Adjust the Spindle of an Automatic High-Speed Stranding Machine"),
    ("全自动高速绞线机主轴的调整对运行精度与稳定至关重要，本文详细介绍调整方法与注意事项。",
     "Spindle adjustment is critical to accuracy and stability of automatic high-speed stranding machines. This article details the methods and precautions."),
    ("押出机设备生产作业员安全注意须知",
     "Safety Guidelines for Extruder Machine Operators"),
    ("押出机运行过程中存在高温、高速等风险，作业人员应严格遵守操作规范，确保安全生产。",
     "Extruders involve high temperature and high-speed risks. Operators must strictly follow procedures to ensure safe production."),
    ("查看全部动态", "View All Updates"),
    # CTA
    ("需要线缆设备解决方案？", "Need Cable Machinery Solutions?"),
    ("告诉我们您的线缆结构与工艺要求，庆丰将为您提供最合适的技术方案。",
     "Tell us your cable structure and process requirements, and Qingfeng will provide the most suitable technical solution."),
    ("联系我们 →", "Contact Us"),
    # alt texts
    ('alt="电动汽车线缆绞线设备"', 'alt="EV charging cable stranding machine"'),
    ('alt="深圳某知名企业EV线缆设备现场"', 'alt="EV cable equipment at a leading Shenzhen factory"'),
    ('alt="出口美国300笼绞机"', 'alt="300 cage strander exported to the USA"'),
    ("庆丰电工机械工厂", "Qingfeng Electrical Machinery Factory"),
    ("行业技术", "Technology"),
]
idx = {"pairs": index_pairs}
D["index.html"] = idx
io.open(ROOT + "_i18n_body_en.json", "w", encoding="utf-8").write(json.dumps(D, ensure_ascii=False, indent=1))
print("index written, total pages:", len(D))